SUBDIR+=buffer-append1
SUBDIR+=buffer-cut1
SUBDIR+=buffer-equal1
SUBDIR+=buffer-ops1
SUBDIR+=buffer-prefix1
SUBDIR+=buffer-return1
SUBDIR+=buffer-segment-pullup1
SUBDIR+=buffer-split1
SUBDIR+=buffer-split-join1

include ../../common/subdir.mk
