TEST=promiscuous-sockets1

TOPDIR=../../../..
USE_LIBS=common common/thread common/time event io io/pipe io/socket

# XXX temporary until uinet lib.mk is in place
LDADD+= -lssl

include ${TOPDIR}/common/program.mk
